### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by strnadmichal** [deta/tela#3]
Hi! I would love to try out your liblary but I'm having an issue with installation. 

First when I tried installing your liblary I got this error

```
npm ERR! code 1
npm ERR! path C:\Users\...\node_modules\@deta\tela\node_modules\esbuild
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! C:\Users\...\node_modules\@deta\tela\node_modules\esbuild\install.js:132
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Expected "0.18.20" but got "0.19.12"
npm ERR!     at validateBinaryVersion (C:\Users\...\node_modules\@deta\tela\node_modules\esbuild\install.js:132:11)
npm ERR!     at C:\Users\...\node_modules\@deta\tela\node_modules\esbuild\install.js:283:5
npm ERR!
npm ERR! Node.js v20.11.0
```

But as I was able to resolve that by instaling older version of esbuild another obstacle come into way.

```
Missing C:\Users\...\node_modules\@deta\tela\svelte.config.js — skipping
> src\lib does not exist
    at do_build (file:///C:/Users/.../node_modules/@deta/tela/node_modules/@sveltejs/package/src/index.js:28:9)
    at Module.build (file:///C:/Users/.../node_modules/@deta/tela/node_modules/@sveltejs/package/src/index.js:16:8)
    at file:///C:/Users/.../node_modules/@deta/tela/node_modules/@sveltejs/package/src/cli.js:49:61
```

And I dot know how to move from here. Is it possible I'm using wrong version of Svelte altogether? I don't quite understand the concept of  "manually build tela as installing it from github does only ship the source files." 
I'm new in this stuff so I'm sorry it's something trivial. :) Thanks!

**Comment by zarSou9** [comment]
I am also getting the exact same issue
